import React from 'react'
import Head from 'next/head'

export default function Header() {
  return (
    <div>
      <Head>
        <title>Tugas Intro Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/telur.png" />
      </Head>
    </div>
  )
}




